### ISSUE TITLE
Running tests fails on Windows 10

### ISSUE THREAD

**Issue by Archomeda** [queicherius/abc-environment#35]
I was using this in your [gw2api-client](https://github.com/queicherius/gw2api-client) on my Windows 10 pc, but running `npm test` fails in Windows's native environment. Running the same command in the Ubuntu Bash (via the Linux subsystem) works fine.

My environment:
- Windows 10 Professional x64
- Node v6.4.0
- npm v4.2.0
- Running this in PowerShell

Output:
```text
> gw2api-client@5.1.0 test ******\gw2api-client
> abc test && abc lint

�  Running tests in `tests/`
module.js:457
    throw err;
    ^

Error: Cannot find module '******\gw2api-client\tests\cache'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at ******\gw2api-client\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (******\gw2api-client\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (******\gw2api-client\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (******\gw2api-client\node_modules\mocha\bin\_mocha:459:18)
    at Module._compile (module.js:556:32)
    at Module.replacementCompile (******\gw2api-client\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (******\gw2api-client\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at ******\gw2api-client\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at require.extensions.(anonymous function) (******\gw2api-client\node_modules\babel-register\lib\node.js:152:7)
    at Object.<anonymous> (******\gw2api-client\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
    at Function.runMain (C:\Users\<USER>\.node-spawn-wrap-8448-af779e32eae7\node:40:10)
    at Object.<anonymous> (******\gw2api-client\node_modules\nyc\bin\wrap.js:22:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
    at Object.<anonymous> (C:\Users\<USER>\.node-spawn-wrap-8448-af779e32eae7\node:140:8)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by queicherius** [comment]
- Can confirm this fails on windows using cmder as well.
- It only happens on *some* parts of the unit test (the `cache` folder) for some reason :thinking:
- It does not matter what's actually in the unit test (a empty test with one `expect` throws the same error)

Gonna poke this some more the next few days. Might have something to do with globbing.

**Comment by queicherius** [comment]
No longer maintaining this
